# Generated by Django 4.2.1 on 2023-05-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='tour_name',
        ),
        migrations.AlterField(
            model_name='airlines',
            name='country_name',
            field=models.ForeignKey(help_text='Страна базирования', max_length=60, on_delete=django.db.models.deletion.CASCADE, to='catalog.countries'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='country_name',
            field=models.ForeignKey(help_text='Страна базирования', max_length=60, on_delete=django.db.models.deletion.CASCADE, to='catalog.countries'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='hotels_name',
            field=models.ForeignKey(help_text='Страна тура', max_length=60, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_name', to='catalog.hotels'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='name',
            field=models.CharField(help_text='Название тура', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tours',
            name='travel_complany_name',
            field=models.ForeignKey(help_text='Туристическая компания', max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='travel_complany_name', to='catalog.travelcompanies'),
        ),
        migrations.AlterField(
            model_name='travelcompanies',
            name='country_name',
            field=models.ForeignKey(help_text='Страна базирования', max_length=60, on_delete=django.db.models.deletion.CASCADE, to='catalog.countries'),
        ),
    ]
