# Generated by Django 4.2.1 on 2023-05-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_buyers_tour_name_alter_airlines_country_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyers_id', models.ForeignKey(help_text='id покупателя', on_delete=django.db.models.deletion.CASCADE, to='catalog.buyers')),
                ('tours_name', models.ForeignKey(help_text='название тура', on_delete=django.db.models.deletion.CASCADE, to='catalog.tours')),
            ],
        ),
    ]
