# Generated by Django 4.2.1 on 2023-05-10 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор'),
        ),
    ]
