# Generated by Django 4.2.1 on 2023-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_travelcompanies_trave_company_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_pic',
            field=models.ImageField(default='C:\\Users\\Dooplik\\Desktop\\Education\\Tours\\TourStore\\catalog\\static\\media\\cit.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='tour_pic',
            field=models.ImageField(default='C:\\Users\\Dooplik\\Desktop\\Education\\Tours\\TourStore\\catalog\\static\\media\\cit.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='travelcompanies',
            name='trave_company_pic',
            field=models.ImageField(default='C:\\Users\\Dooplik\\Desktop\\Education\\Tours\\TourStore\\catalog\\static\\media\\cit.jpg', upload_to='img/'),
        ),
    ]
