# Generated by Django 4.2.1 on 2023-05-12 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_trave_company_pic_travelcompanies_travel_company_pic'),
    ]

    operations = [

    ]
