# Generated by Django 4.2.1 on 2023-05-12 17:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_flights_tour_name_alter_tours_id_and_more'),
    ]

    operations = [

    ]
