# Generated by Django 4.2.1 on 2023-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_flights_tour_name_alter_tours_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='flights_name',
            field=models.ManyToManyField(through='catalog.Flights', to='catalog.airlines'),
        ),
    ]
