# Generated by Django 4.2.1 on 2023-05-12 18:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_tours_flights_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='tour_name',
            field=models.ForeignKey(help_text='Название тура', on_delete=django.db.models.deletion.CASCADE, related_name='tour_name', to='catalog.tours'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='name',
            field=models.CharField(help_text='Название тура', max_length=45, primary_key=True, serialize=False),
        ),
    ]
