# Generated by Django 4.2.1 on 2023-05-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_flights_tour_name_alter_tours_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='description',
            field=models.TextField(default='Тут должно быть описание тура', help_text='Описание тура', max_length=500),
        ),
    ]
