# Generated by Django 4.2.1 on 2023-05-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_tours_description_alter_tours_hotels_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='tour_from',
            field=models.ForeignKey(default='Россия', help_text='Откуда летим', max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='tour_from', to='catalog.countries'),
        ),
        migrations.AddField(
            model_name='tours',
            name='tour_in',
            field=models.ForeignKey(default='Россия', help_text='Куда летим', max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='tour_in', to='catalog.countries'),
        ),
    ]
