# Generated by Django 4.2.1 on 2023-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_tours_tour_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='end_date',
            field=models.DateField(help_text='Дата окончания тура'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='start_date',
            field=models.DateField(help_text='Дата начала тура'),
        ),
    ]
